version: "3.9"
services:
  dolar_server:
    build: .
    ports:
      - "8000:8000"
    links:
      - mon
  mon:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=example
    